### ISSUE TITLE
OWD Project Proposal: WebXR Browser Compatibility

### ISSUE THREAD

**Issue by JoelMarcey** [openwebdocs/project#35] opened 2021-05-17 20:18 UTC
# WebXR Browser Compatibility

MDN has an essential feature where it provides [browser compatibility data](https://github.com/mdn/browser-compat-data) for its documented web technologies, including web APIs, JavaScript and HTML. This compatibility is usually represented via a [table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH-Lifetime#browser_compatibility) of browsers, and is essential reading for developers to ensure their apps will be usable across the widest variety of browser platforms.

Currently, the represented browsers in these tables are the common and widely used desktop and mobile browsers. And while this data is of course necessary because of the broad use of these browsers, there are other browser categories that should also be considered when it comes to compatibility.

Virtual and augmented reality (VR and AR, collectively “XR”) devices are becoming more common in households and the industry. These devices have web browsers and WebXR provides the functionality and APIs to the web to those devices. In fact, WebXR is becoming so mainstream that MDN is starting to [officially document it](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals). 

## Proposal

Given the increasing use of XR devices, XR should be added alongside desktop and phones in the compatibility tables on MDN. Mozilla Mixed Reality and Facebook’s Oculus Browser are examples of browsers for XR devices which could appear here. We expect browsers which work on desktops and phones, but support XR features, would continue to appear under their primary modality of desktop/phone. 

Each browser vendor would provide the necessary data, in the JSON necessary format, to be added to the [compatibility repo](https://github.com/mdn/browser-compat-data/tree/main/browsers). And then that data would be exported into the MDN documentation.

The proposal is as follows:

1. An extra column would be added to the compatibility tables called “XR Devices”, with an icon such as ![Slice 1](https://user-images.githubusercontent.com/3757713/118546219-7e37aa80-b70c-11eb-851c-5866f0bbdf58.png), where native XR-based browsers would be listed.
2. Facebook will work to provide Oculus Browser compatibility data in [browser-compat-data](https://github.com/mdn/browser-compat-data). Facebook would like Oculus Browser to appear in the XR Devices column.

_Note: Facebook would like feedback on what level of coverage OWD needs to see for (2)._

Facebook has noticed some recent XR _features_ are missing from [browser-compat-data](https://github.com/mdn/browser-compat-data). Facebook can update missing XR-specific features as it publishes its compatibility data. This will make it easier for other vendors and community contributors to publish updated compatibility data for XR features in other browsers.

**Comment by Elchi3** [comment] 2021-06-15 12:02
We've met last Wednesday (June 9th, 2021) to assess this project. We think it's suitable for us to work on this topic and it seems reasonably scoped to take on within a quarter. The following priority assessment was made:

# Priority assessment

This table checks this project against the [OWD prioritization criteria](https://github.com/openwebdocs/project/blob/main/steering-committee/prioritization-criteria.md).

| Criteria 	| Assessment | Points |
|---------|-------------| ------ |
| Effort | Medium/Large. Comments: <br> For better estimation: Figure out how much data we need where <br> Maybe get a sample data set <br> Need to figure out what this means for BCD first, then how to render it <br> Also, how much is engine data vs browser specific data? <br> Workload can be shared given Facebook can help with the work and other immersive Web folks likely, too | -2 |
| Dependencies | Figuring out how this fits into BCD <br> Writing WebXR docs (can be a separate project afterwards or in parallel) | -1 |
| Community enablement | Enables the Immersive Web community | 1 |
| Momentum | High. The core spec is stable, devices become more common in households and the industry | 2 |
| Enabling learners | N/A | 0 |
| Enabling professionals | Medium to high. Professionals need to know the compatibility of XR tech and to what extend features are available | 1,5 |
| Underrepresented topics / ethical web | N/A | 0 |
| Operational necessities | N/A | 0 |
| Addressing needs of the Web industry | We think this addresses needs very much, but no survey or other data points have been presented to show a high demand | 1

**Comment by Elchi3** [comment] 2021-07-22 07:08
I've started to get more familiar with WebXR and as a first step I took a look at the existing MDN WebXR reference pages. I made a pass to clean them, to show compat tables properly, and have a consistent structure. (no dictionaries, enums, callback pages anymore -- this was wrong according to the MDN reference guidelines and BCD data structures). This should be all in shape now.

MDN and the compat data mark almost everything related to WebXR as "experimental". Here I would appreciate some subject matter advice which parts of the API should really be considered "experimental"/"unstable" and which not.

@dominiccooney and I also chatted a bit about landing pages and we should clean them up some more and give a better overview of the core WebXR Device API and all the available extensions/modules.

I've also identified missing reference pages and I think a good next step is for me to create them. This is the list of features where we know (thanks to the compat data) that implementations exist but MDN docs haven't been written yet. Of course, if other WebXR browsers implement more features, please let me know and also add it to the compat data!
 
XRAnchor
XRAnchor.anchorSpace
XRAnchor.delete
XRAnchorSet
XRCPUDepthInformation
XRCPUDepthInformation.data
XRCPUDepthInformation.getDepthInMeters
XRDepthInformation
XRDepthInformation.height
XRDepthInformation.normDepthBufferFromNormView
XRDepthInformation.rawValueToMeters
XRDepthInformation.width
XRFrame.createAnchor
XRFrame.getDepthInformation
XRFrame.getHitTestResults
XRFrame.getHitTestResultsForTransientInput
XRFrame.getLightEstimate
XRFrame.trackedAnchors
XRHitTestResult
XRHitTestResult.createAnchor
XRHitTestResult.getPose
XRHitTestSource
XRHitTestSource.cancel
XRLayer
XRLightEstimate
XRLightEstimate.primaryLightDirection
XRLightEstimate.primaryLightIntensity
XRLightEstimate.sphericalHarmonicsCoefficients
XRLightProbe
XRLightProbe.onreflectionchange
XRLightProbe.probeSpace
XRRay
XRRay.XRRay
XRRay.direction
XRRay.matrix
XRRay.origin
XRSession.depthDataFormat
XRSession.depthUsage
XRSession.requestHitTestSourceForTransientInput
XRSession.requestLightProbe
XRTransientInputHitTestResult
XRTransientInputHitTestResult.inputSource
XRTransientInputHitTestResult.results
XRTransientInputHitTestSource
XRTransientInputHitTestSource.cancel
XRView.isFirstPersonObserver
XRView.recommendedViewportScale
XRView.requestViewportScale
XRWebGLBinding
XRWebGLBinding.XRWebGLBinding
XRWebGLBinding.getDepthInformation
XRWebGLBinding.getReflectionCubeMap
XRWebGLDepthInformation
XRWebGLDepthInformation.texture

**Comment by Elchi3** [comment] 2021-07-28 10:29
What's missing in the compat data (and also on MDN) are features [implemented by Oculus](https://developer.oculus.com/documentation/oculus-browser/browser-release-notes/).

- https://immersive-web.github.io/layers/ (enabled by default in Oculus 16.1)
- https://immersive-web.github.io/webxr-hand-input/ (enabled by default in Oculus 15.1)
- XRPose.angularVelocity & XRPose.linearVelocity (shipped in Oculus 15.0)
- (maybe more)

**Comment by Elchi3** [comment] 2021-07-29 13:58
Compared the core spec's IDL with what we have on MDN. A few (new) features that are undocumented came up and it's unclear if anyone implements them (yet).

XRSession.frameRate
XRSession.supportedFrameRates
XRSession.updateTargetFrameRate
XRSession.onframeratechange
XRView.recommendedViewportScale
XRView.requestViewportScale
XRWebGLLayer.fixedFoveation

**Comment by dominiccooney** [comment] 2021-07-30 22:49
These are in various stages but all of these are experimental or shipped in some browser: Oculus Browser has the frame rate APIs behind an experimental flag; we think Chrome for Android implements the viewport scale, some browsers have the property but it's a no-op; Oculus Browser has shipped fixedFoveation but I think we are the only one. (Caveat: My knowledge of Samsung Internet's VR support and Hololens/Edge's VR support is very limited.)

**Comment by Elchi3** [comment] 2021-09-23 19:17
I've finished most of this work. Q3 comes to an end and over the course of this quarter, I have: 

- documented features from 10 WebXR specifications
- wrote 131 new MDN reference pages 
- submitted 78 pull requests to MDN for this work
- submitted 4 pull requests to immversive-web specifications/explainers
- converted the MDN WebXR docs from HTML to Markdown

My mandate here still includes to help getting the Oculus browser compat data into BCD and getting the missing support statements in. @dominiccooney is driving this, though. The issue is https://github.com/mdn/browser-compat-data/issues/12303. 

After that's done, I'll close this issue and work on something new. See https://github.com/openwebdocs/project/issues/55 for Q4 planning which also includes a new WebXR-related project: [WebXR guides](https://github.com/mdn/content/issues/7276). If you are an OWD Steering Committee member, you can vote it up so it will be considered.

I would like to thank Ada Rose Cannon (@AdaRoseCannon, Samsung Internet), Dominic Cooney (@dominiccooney , Facebook), and Joe Medley (@jpmedley, Google) for helping with reviews and code examples and their support in the #webxr-docs OWD slack channel.

**Comment by JoelMarcey** [comment] 2021-09-24 18:50
Thanks for the great work everyone! This is so awesome to see.

**Comment by AdaRoseCannon** [comment] 2021-09-24 19:18
This is totally incredible work, thank you for all of it!! I am sure it is
already being a massive benefit for WebXR Developers.

**Comment by Elchi3** [comment] 2022-02-09 11:23
Closing this but I'm encouraging the WebXR community to file new issues with OWD if there are new things we should add to MDN/BCD.

Adding Oculus to BCD/MDN is discussed in the following issues/PRs and is in @dominiccooney's hands.  
https://github.com/mdn/browser-compat-data/pull/12642
https://github.com/mdn/browser-compat-data/issues/12303

An issue about more WebXR guide material is https://github.com/mdn/content/issues/7276

**Closed by Elchi3** 2022-02-09 11:23 UTC
